### ISSUE TITLE
Black page appears after login

### ISSUE THREAD

**Issue by clawer87** [davereese/beerforge#4]
Hi,
I've tried running the app, and it runs fine, and I get the homepage.  After creating a new user and logging in, I get an error.
TypeError: schema is undefined in src/components/Avatar/Avatar.tsx:26

<img width="875" alt="Screen Shot 2020-02-13 at 4 30 49 PM" src="https://user-images.githubusercontent.com/17443500/74484458-39282700-4e7e-11ea-8d00-ee13921fb0e7.png">

I'm thinking maybe it's a problem with my install.  All I did was clone and run npm start.  I did change the port to 5000, since I have another app running on 3000.  I've been using typescript@latest, since every time I tried compiling it with something before 5.0.0 as recommended, I get a compilation error.  I'm wondering did I miss a database setup or something?

**Comment by davereese** [comment]
Yes, the database is all in a separate repo. I only have the front end repo public. I figured that was the more complicated one anyway.

**Comment by clawer87** [comment]
Got it.  Thanks.
